general:
  # Whether to show floating windows as always on top.
  show_floating_on_top: true

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to globally enable/disable window transition animations (on minimize, close,
  # etc). Set to 'unchanged' to make no setting changes.
  window_animations: "false"

  cursor_jump:
    enabled: true
    trigger: "window_focus"

gaps:
  inner_gap: "6px"
  outer_gap:
    top: "46px" # account for bar
    right: "6px"
    bottom: "6px"
    left: "6px"

# maybe doesn't work anymore?
bar:
  enabled: true
  height: "20px"
  position: "top"
  always_on_top: false
  opacity: 1.0
  # background: "#181825"
  background: "#11111b"
  # background: "#20242cc4"
  foreground: "#cdd6f4"
  # foreground: "#ffffff"
  # font_family: "Segoe UI"
  font_family: "Cascadia Code NFM"
  font_size: "13 px"
  padding: "2 px"
  # margin: "10px 10px"
  offset_x: "0"
  offset_y: "0"
  # border_width: "2px"
  # border_color: "#313244"
  # border_radius: "2px"
  components_left:
    - type: "workspaces"
      # focused_workspace_background: "#ffffff33"
      focused_workspace_background: "#313244"
      # displayed_workspace_background: "#00000033"
      displayed_workspace_background: "#1e1e2e"
      default_workspace_background: "#181825"
      # margin: "0 2px"
      padding: "0 4px"
    # - type: "system tray"
    #   label_expand_text: "<"
    #   label_collapse_text: ">"
  components_center:
    - type: "window title"
      foreground: "#cdd6f4"
  components_right:
    - type: "cpu"
      label: "cpu({percent_usage}%)"
      refresh_interval_ms: 2000
      background: "#181825"
      padding: "0 4px"
    - type: "memory"
      label: "ram({percent_usage}%)"
      refresh_interval_ms: 2000
      background: "#181825"
      padding: "0 4px"
    # - type: "gpu"
    #   label: "gpu({percent_usage}%)"
    #   refresh_interval_ms: 2000
    #   background: "#181825"
    #   padding: "0 4px"
    # - type: "network"
    #   label_no_internet: "NC "
    #   label_ethernet: "Eth "
    #   label_wifi_strength_0: "WiFi: 0%"
    #   label_wifi_strength_25: "WiFi: 25%"
    #   label_wifi_strength_50: "WiFi: 50%"
    #   label_wifi_strength_75: "WiFi: 75%"
    #   label_wifi_strength_100: "WiFi: 100%"
    #   background: "#181825"
    #   padding: "0 4px"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      # background: "#1e1e2e"
      background: "#181825"
      padding: "0 4px"
      # margin: "0 0px"
      # background: "#ffffff33"
    - type: "binding mode"
      background: "#ffffff33"
      # margin: "0 4px 0 0"
      padding: "0 0 0 4px"
    # - type: "clock"
      # # Documentation on formatting date/time string:
      # # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      # time_formatting: "hh:mm tt  ddd MMM d"
      # margin: "0 0 0 10px"


window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'

workspaces: # maybe see windows display settings for monitor identification
  - name: "1"
    bind_to_monitor: 3 # left
  - name: "2"
    bind_to_monitor: 1 # middle
  - name: "3"
    bind_to_monitor: 2 # right
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
  - name: "10"
    bind_to_monitor: 2 # also right(?)

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  # - command: "ignore"
    # match_process_name: "Taskmgr"
    # match_title: "/.*/"

  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # fix for screen snipping/snip and sketch/win+s screenshot key
      - window_title: { equals: "Screen Snipping" }
      - window_process: { regex: "/ScreenSketch|ScreenClippingHost/" }

      - window_process: { regex: "/voicemeeter8|Taskmgr|Message/" }

      - window_class: { regex: "/Afx:00D60000:8:00010003:00000000:00B1086D|WdcWindow/" } # some old window class

  - commands: ["set-floating"]
    match:
      # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
      - window_class: { regex: "/#32770|#32768|SunAwtDialog/" } # also fixes jetbrains IDE dialog winodws
      # certain programs should not tile for jank reasons
      - window_process: { regex: "/WizTree64|Godot.*|javaw/" }

      # jetbrains IDE floats
      # window_process: { regex: "/rustrover64|rider64|idea64|clion64/" }
      - window_class: { equals: "SunAwtDialog" }
      - window_title: { regex: "/Welcome|Settings|Inline|Refactor|Reformat|Open File|Run/Debug Configurations|Select Methods|Internal Error|Environment Variables/" }

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  # - commands: ["resize 0px -7px -7px -7px"] # this doesn't currently work?
    # match:
      # - window_process: { regex: "/steam|steamwebhelper|Fork/" }

  - commands: ["move --workspace 3"]
    match:
      # - window_title: "Bevy Jam 5" # move bevy app on instantiation (for development)

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - commands: ["resize --width -2%"]
        bindings: ["H", "Left"]
      - commands: ["resize --width +2%"]
        bindings: ["L", "Right"]
      - commands: ["resize --height +2%"]
        bindings: ["K", "Up"]
      - commands: ["resize --height -2%"]
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - commands: ["shell-exec wt"] # originally 'shell-exec cmd'
    bindings: ["alt+enter"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['alt+s']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']
  # extra
  - commands: ['move --workspace 10', 'focus --workspace 10']
    bindings: ['alt+shift+0']
